# Generated by Django 5.1 on 2024-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_quantity', models.IntegerField()),
                ('product_supplier', models.CharField(max_length=50)),
            ],
        ),
    ]
